// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/event/event.proto

package eventpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	TotalSeats     int32                  `protobuf:"varint,3,opt,name=total_seats,json=totalSeats,proto3" json:"total_seats,omitempty"`
	AvailableSeats int32                  `protobuf:"varint,4,opt,name=available_seats,json=availableSeats,proto3" json:"available_seats,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_event_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_event_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event) GetTotalSeats() int32 {
	if x != nil {
		return x.TotalSeats
	}
	return 0
}

func (x *Event) GetAvailableSeats() int32 {
	if x != nil {
		return x.AvailableSeats
	}
	return 0
}

type CreateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	TotalSeats    int32                  `protobuf:"varint,2,opt,name=total_seats,json=totalSeats,proto3" json:"total_seats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	mi := &file_proto_event_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_event_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEventRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateEventRequest) GetTotalSeats() int32 {
	if x != nil {
		return x.TotalSeats
	}
	return 0
}

type CreateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventResponse) Reset() {
	*x = CreateEventResponse{}
	mi := &file_proto_event_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventResponse) ProtoMessage() {}

func (x *CreateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventResponse.ProtoReflect.Descriptor instead.
func (*CreateEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_event_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEventResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type GetEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventRequest) Reset() {
	*x = GetEventRequest{}
	mi := &file_proto_event_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventRequest) ProtoMessage() {}

func (x *GetEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventRequest.ProtoReflect.Descriptor instead.
func (*GetEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_event_proto_rawDescGZIP(), []int{3}
}

func (x *GetEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventResponse) Reset() {
	*x = GetEventResponse{}
	mi := &file_proto_event_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventResponse) ProtoMessage() {}

func (x *GetEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventResponse.ProtoReflect.Descriptor instead.
func (*GetEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_event_proto_rawDescGZIP(), []int{4}
}

func (x *GetEventResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type ListEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_proto_event_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_event_proto_rawDescGZIP(), []int{5}
}

type ListEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_proto_event_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_event_proto_rawDescGZIP(), []int{6}
}

func (x *ListEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type ReserveSeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveSeatRequest) Reset() {
	*x = ReserveSeatRequest{}
	mi := &file_proto_event_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveSeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveSeatRequest) ProtoMessage() {}

func (x *ReserveSeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveSeatRequest.ProtoReflect.Descriptor instead.
func (*ReserveSeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_event_proto_rawDescGZIP(), []int{7}
}

func (x *ReserveSeatRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type ReserveSeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveSeatResponse) Reset() {
	*x = ReserveSeatResponse{}
	mi := &file_proto_event_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveSeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveSeatResponse) ProtoMessage() {}

func (x *ReserveSeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveSeatResponse.ProtoReflect.Descriptor instead.
func (*ReserveSeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_event_proto_rawDescGZIP(), []int{8}
}

func (x *ReserveSeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ReleaseSeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseSeatRequest) Reset() {
	*x = ReleaseSeatRequest{}
	mi := &file_proto_event_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseSeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseSeatRequest) ProtoMessage() {}

func (x *ReleaseSeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseSeatRequest.ProtoReflect.Descriptor instead.
func (*ReleaseSeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_event_proto_rawDescGZIP(), []int{9}
}

func (x *ReleaseSeatRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type ReleaseSeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseSeatResponse) Reset() {
	*x = ReleaseSeatResponse{}
	mi := &file_proto_event_event_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseSeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseSeatResponse) ProtoMessage() {}

func (x *ReleaseSeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_event_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseSeatResponse.ProtoReflect.Descriptor instead.
func (*ReleaseSeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_event_proto_rawDescGZIP(), []int{10}
}

func (x *ReleaseSeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_event_event_proto protoreflect.FileDescriptor

const file_proto_event_event_proto_rawDesc = "" +
	"\n" +
	"\x17proto/event/event.proto\x12\x05event\"w\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1f\n" +
	"\vtotal_seats\x18\x03 \x01(\x05R\n" +
	"totalSeats\x12'\n" +
	"\x0favailable_seats\x18\x04 \x01(\x05R\x0eavailableSeats\"K\n" +
	"\x12CreateEventRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1f\n" +
	"\vtotal_seats\x18\x02 \x01(\x05R\n" +
	"totalSeats\"9\n" +
	"\x13CreateEventResponse\x12\"\n" +
	"\x05event\x18\x01 \x01(\v2\f.event.EventR\x05event\"!\n" +
	"\x0fGetEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"6\n" +
	"\x10GetEventResponse\x12\"\n" +
	"\x05event\x18\x01 \x01(\v2\f.event.EventR\x05event\"\x13\n" +
	"\x11ListEventsRequest\":\n" +
	"\x12ListEventsResponse\x12$\n" +
	"\x06events\x18\x01 \x03(\v2\f.event.EventR\x06events\"/\n" +
	"\x12ReserveSeatRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"/\n" +
	"\x13ReserveSeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"/\n" +
	"\x12ReleaseSeatRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"/\n" +
	"\x13ReleaseSeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xe0\x02\n" +
	"\fEventService\x12D\n" +
	"\vCreateEvent\x12\x19.event.CreateEventRequest\x1a\x1a.event.CreateEventResponse\x12;\n" +
	"\bGetEvent\x12\x16.event.GetEventRequest\x1a\x17.event.GetEventResponse\x12A\n" +
	"\n" +
	"ListEvents\x12\x18.event.ListEventsRequest\x1a\x19.event.ListEventsResponse\x12D\n" +
	"\vReserveSeat\x12\x19.event.ReserveSeatRequest\x1a\x1a.event.ReserveSeatResponse\x12D\n" +
	"\vReleaseSeat\x12\x19.event.ReleaseSeatRequest\x1a\x1a.event.ReleaseSeatResponseB%Z#booking-service/event/proto;eventpbb\x06proto3"

var (
	file_proto_event_event_proto_rawDescOnce sync.Once
	file_proto_event_event_proto_rawDescData []byte
)

func file_proto_event_event_proto_rawDescGZIP() []byte {
	file_proto_event_event_proto_rawDescOnce.Do(func() {
		file_proto_event_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_event_event_proto_rawDesc), len(file_proto_event_event_proto_rawDesc)))
	})
	return file_proto_event_event_proto_rawDescData
}

var file_proto_event_event_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_event_event_proto_goTypes = []any{
	(*Event)(nil),               // 0: event.Event
	(*CreateEventRequest)(nil),  // 1: event.CreateEventRequest
	(*CreateEventResponse)(nil), // 2: event.CreateEventResponse
	(*GetEventRequest)(nil),     // 3: event.GetEventRequest
	(*GetEventResponse)(nil),    // 4: event.GetEventResponse
	(*ListEventsRequest)(nil),   // 5: event.ListEventsRequest
	(*ListEventsResponse)(nil),  // 6: event.ListEventsResponse
	(*ReserveSeatRequest)(nil),  // 7: event.ReserveSeatRequest
	(*ReserveSeatResponse)(nil), // 8: event.ReserveSeatResponse
	(*ReleaseSeatRequest)(nil),  // 9: event.ReleaseSeatRequest
	(*ReleaseSeatResponse)(nil), // 10: event.ReleaseSeatResponse
}
var file_proto_event_event_proto_depIdxs = []int32{
	0,  // 0: event.CreateEventResponse.event:type_name -> event.Event
	0,  // 1: event.GetEventResponse.event:type_name -> event.Event
	0,  // 2: event.ListEventsResponse.events:type_name -> event.Event
	1,  // 3: event.EventService.CreateEvent:input_type -> event.CreateEventRequest
	3,  // 4: event.EventService.GetEvent:input_type -> event.GetEventRequest
	5,  // 5: event.EventService.ListEvents:input_type -> event.ListEventsRequest
	7,  // 6: event.EventService.ReserveSeat:input_type -> event.ReserveSeatRequest
	9,  // 7: event.EventService.ReleaseSeat:input_type -> event.ReleaseSeatRequest
	2,  // 8: event.EventService.CreateEvent:output_type -> event.CreateEventResponse
	4,  // 9: event.EventService.GetEvent:output_type -> event.GetEventResponse
	6,  // 10: event.EventService.ListEvents:output_type -> event.ListEventsResponse
	8,  // 11: event.EventService.ReserveSeat:output_type -> event.ReserveSeatResponse
	10, // 12: event.EventService.ReleaseSeat:output_type -> event.ReleaseSeatResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_event_event_proto_init() }
func file_proto_event_event_proto_init() {
	if File_proto_event_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_event_event_proto_rawDesc), len(file_proto_event_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_event_event_proto_goTypes,
		DependencyIndexes: file_proto_event_event_proto_depIdxs,
		MessageInfos:      file_proto_event_event_proto_msgTypes,
	}.Build()
	File_proto_event_event_proto = out.File
	file_proto_event_event_proto_goTypes = nil
	file_proto_event_event_proto_depIdxs = nil
}
